projects:
  vysae:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: r5s5fmi7cnawzefibjmwlnpkry
      endpoints:
        prod: >-
          https://pg5uripmh5acbelm3g5yb2dyr4.appsync-api.eu-west-1.amazonaws.com/graphql
