service: backend

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-appsync-plugin

custom:
  serverless-offline:
    port: 4000
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: Vysae
            sources: [seedData/vysae.json]
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      packagePath: './package.json'
    packager: 'npm'
  appSync:
    name: Vysae
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: eu-west-1
      defaultAction: ALLOW
      userPoolId: eu-west-1_MUEHMQ2R2
    mappingTemplatesLocation: "./mapping-templates"
    mappingTemplates:
      - dataSource: CompanyTable
        type: Mutation
        field: createCompany
        request: "MutationCreateCompany-request.vm"
        response: "MutationCreateCompany-response.vm"
      - dataSource: CompanyTable
        type: Query
        field: getCompany
        request: "QueryGetCompany-request.txt"
        response: "QueryGetCompany-response.txt"
      - dataSource: Vysae
        type: Company
        field: shareholders
        request: "company-shareholders-request.txt"
        response: "company-shareholders-response.txt"
      - dataSource: Vysae
        type: Company
        field: meetings
        request: "company-meetings-request.txt"
        response: "company-meetings-response.txt"
      - dataSource: UserTable
        type: Query
        field: getUser
        request: "QueryGetUser-request.vm"
        response: "QueryGetUser-response.vm"
      - dataSource: UserCompanyConnectionTable
        type: User
        field: companies
        request: "User-companies-request.vm"
        response: "User-companies-response.vm"
      - dataSource: CompanyTable
        type: UserCompanyConnection
        field: items
        request: "UserCompanyConnection-items-request.vm"
        response: "UserCompanyConnection-items-response.vm"
      - dataSource: ShareholderTable
        type: Mutation
        field: createShareholder
        request: "MutationCreateShareholder-request.vm"
        response: "MutationCreateShareholder-response.vm"
      - dataSource: Vysae
        type: Meeting
        field: agreements
        request: "meeting-agreements-request.txt"
        response: "meeting-agreements-response.txt"
      - dataSource: Vysae
        type: Query
        field: getMeeting
        request: "QueryGetMeeting-request.txt"
        response: "QueryGetMeeting-response.txt"
      - dataSource: Vysae
        type: Mutation
        field: createMeeting
        request: "MutationCreateMeeting-request.txt"
        response: "MutationCreateMeeting-response.txt"
      - dataSource: Vysae
        type: Mutation
        field: createVotesForAgreements
        request: "MutationCreateVotesForAgreements-request.txt"
        response: "MutationCreateVotesForAgreements-response.txt"
      - dataSource: meetingDocx
        type: Query
        field: queryMeetingDocx
        request: "queryMeetingDocx-request.txt"
        response: "queryMeetingDocx-response.txt"
      - dataSource: Vysae
        type: Agreement
        field: votes
        request: "Agreement-votes-request.txt"
        response: "Agreement-votes-response.txt"
      - dataSource: Vysae
        type: Shareholder
        field: companies
        request: "shareholder-companies-request.txt"
        response: "shareholder-companies-response.txt"
      - dataSource: createUser 
        type: Mutation
        field: createUser
        request: "MutationCreateUser-request.vm"
        response: "MutationCreateUser-response.vm"
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: UserTable
        description: "User table"
        config:
          tableName: { Ref: "VysaeUserTable" }
          serviceRoleArn: "arn:aws:iam::${env:AWS_ACCOUNTID}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AMAZON_DYNAMODB
        name: CompanyTable
        description: "Company table"
        config:
          tableName: { Ref: "VysaeCompanyTable" }
          serviceRoleArn: "arn:aws:iam::${env:AWS_ACCOUNTID}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AMAZON_DYNAMODB
        name: UserCompanyConnectionTable
        description: "UserCompanyConnection table"
        config:
          tableName: { Ref: "VysaeUserCompanyConnectionTable" }
          serviceRoleArn: "arn:aws:iam::${env:AWS_ACCOUNTID}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AMAZON_DYNAMODB
        name: ShareholderTable
        description: "Shareholder table"
        config:
          tableName: { Ref: "VysaeShareholderTable" }
          serviceRoleArn: "arn:aws:iam::${env:AWS_ACCOUNTID}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AMAZON_DYNAMODB
        name: UserShareholderConnectionTable
        description: "UserShareholderConnection table"
        config:
          tableName: { Ref: "VysaeUserShareholderConnectionTable" }
          serviceRoleArn: "arn:aws:iam::${env:AWS_ACCOUNTID}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AMAZON_DYNAMODB
        name: CompanyShareholderConnectionTable
        description: "CompanyShareholderConnection table"
        config:
          tableName: { Ref: "VysaeCompanyShareholderConnectionTable" }
          serviceRoleArn: "arn:aws:iam::${env:AWS_ACCOUNTID}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AMAZON_DYNAMODB
        name: Vysae
        description: "Vysae table"
        config:
          tableName: { Ref: "Vysae" }
          serviceRoleArn: "arn:aws:iam::${env:AWS_ACCOUNTID}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AWS_LAMBDA
        name: meetingDocx
        description: "get Docxpresso URL for convening a meeting"
        config:
          lambdaFunctionArn: { Fn::GetAtt: [MeetingDocxLambdaFunction, Arn] }
          serviceRoleArn: "arn:aws:iam::${env:AWS_ACCOUNTID}:role/Lambda-${self:custom.appSync.serviceRole}"
      - type: AWS_LAMBDA
        name: createUser
        description: "create User ( Cognito & DynamoDB )"
        config:
          lambdaFunctionArn: { Fn::GetAtt: [CreateUserLambdaFunction, Arn] }
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }

functions:
  meetingDocx:
    environment:
      DOCX_API_KEY: $(file(./config.js):docxAPIKEY)
    handler: handler.meetingDocx
    events:
      - http:
          path: meeting/docx
          method: get 
  conveneMeeting:
    environment:
      DOCX_API_KEY: $(file(./config.js):docxAPIKEY)
    handler: handler.conveneMeeting
    events:
      - http:
          path: meeting/convene
          method: post
  createUser:
    handler: handler.createUser
    role: DynamoDBServiceRole

resources:
  Resources:
    VysaeUserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: VysaeUser
        AttributeDefinitions:
          - AttributeName: userId 
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
    VysaeCompanyTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: VysaeCompany
        AttributeDefinitions:
          - AttributeName: companyId 
            AttributeType: S
        KeySchema:
          - AttributeName: companyId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
    VysaeShareholderTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: VysaeShareholder
        AttributeDefinitions:
          - AttributeName: shareholderId 
            AttributeType: S
        KeySchema:
          - AttributeName: shareholderId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
    VysaeUserCompanyConnectionTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: VysaeUserCompanyConnection
        AttributeDefinitions:
          - AttributeName: userCompanyConnectionId 
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: companyId
            AttributeType: S
        KeySchema:
          - AttributeName: userCompanyConnectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          - IndexName: User
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3 
              WriteCapacityUnits: 3 
          - IndexName: Company
            KeySchema:
              - AttributeName: companyId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3 
              WriteCapacityUnits: 3 
    VysaeUserShareholderConnectionTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: VysaeUserShareholderConnection
        AttributeDefinitions:
          - AttributeName: userShareholderConnectionId 
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: shareholderId
            AttributeType: S
        KeySchema:
          - AttributeName: userShareholderConnectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          - IndexName: User
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3 
              WriteCapacityUnits: 3 
          - IndexName: Shareholder
            KeySchema:
              - AttributeName: shareholderId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3 
              WriteCapacityUnits: 3 
    VysaeCompanyShareholderConnectionTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: VysaeCompanyShareholderConnection
        AttributeDefinitions:
          - AttributeName: companyShareholderConnectionId 
            AttributeType: S
          - AttributeName: companyId
            AttributeType: S
          - AttributeName: shareholderId
            AttributeType: S
        KeySchema:
          - AttributeName: companyShareholderConnectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          - IndexName: Company
            KeySchema:
              - AttributeName: companyId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3 
              WriteCapacityUnits: 3 
          - IndexName: Shareholder
            KeySchema:
              - AttributeName: shareholderId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3 
              WriteCapacityUnits: 3 
    Vysae:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Vysae
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 3 
          WriteCapacityUnits: 3 
        GlobalSecondaryIndexes:
          - IndexName: GSI
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
              - AttributeName: PK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3 
              WriteCapacityUnits: 3 
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Dynamo-AppSyncServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "Dynamo-AppSyncServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:BatchGetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - "arn:aws:dynamodb:eu-west-1:*:table/Vysae"
                    - "arn:aws:dynamodb:eu-west-1:*:table/Vysae/*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUser"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUser/*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeCompany"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeCompany/*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeShareholder"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeShareholder/*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUserCompanyConnection"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUserCompanyConnection/*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUserShareholderConnection"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUserShareholderConnection/*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeCompanyShareholderConnection"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeCompanyShareholderConnection/*"
    AppSyncLambdaServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Vysae-AppSync-Lambda-ServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "Vysae-AppSync-Lambda-ServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "lambda:InvokeFunction"
                  Resource:
                    - "arn:aws:lambda:eu-west-1:037641059503:function:backend-dev-createUser"
    DynamoDBServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Vysae-Lambda-ServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service: "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: "Vysae-DynamoDB-ServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:BatchGetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUser"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUser/*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeCompany"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeCompany/*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUserCompanyConnection"
                    - "arn:aws:dynamodb:eu-west-1:*:table/VysaeUserCompanyConnection/*"
          - PolicyName: "Vysae-Logs-ServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource:
                    "arn:aws:logs:eu-west-1:037641059503:log-group:/aws/lambda/backend-dev-createUser:*"
