service: backend

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-appsync-plugin

custom:
  serverless-offline:
    port: 4000
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: Vysae
            sources: [seedData/vysae.json]
  appSync:
    name: Vysae
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: eu-west-1
      defaultAction: ALLOW
      userPoolId: eu-west-1_MUEHMQ2R2
    mappingTemplatesLocation: "./mapping-templates"
    mappingTemplates:
      - dataSource: Vysae
        type: Mutation
        field: createCompany
        request: "createCompany-request-mapping-template.txt"
        response: "createCompany-response-mapping-template.txt"
      - dataSource: Vysae
        type: Query
        field: getCompany
        request: "getCompany-request-mapping-template.txt"
        response: "getCompany-response-mapping-template.txt"
      - dataSource: Vysae
        type: Company
        field: shareholders
        request: "company-shareholders-request.txt"
        response: "company-shareholders-response.txt"
      - dataSource: Vysae
        type: Company
        field: meetings
        request: "company-meetings-request.txt"
        response: "company-meetings-response.txt"
      - dataSource: Vysae
        type: Query
        field: getShareholder
        request: "getShareholder-request-mapping-template.txt"
        response: "getShareholder-response-mapping-template.txt"
      - dataSource: Vysae
        type: Shareholder
        field: companies
        request: "shareholder-companies-request.txt"
        response: "shareholder-companies-response.txt"
      - dataSource: Vysae
        type: Meeting
        field: agreements
        request: "meeting-agreements-request.txt"
        response: "meeting-agreements-response.txt"
      - dataSource: Vysae
        type: Agreement
        field: votes
        request: "agreement-votes-request.txt"
        response: "agreement-votes-response.txt"
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Vysae
        description: "Vysae table"
        config:
          tableName: { Ref: "Vysae" }
          serviceRoleArn: "arn:aws:iam::${env:AWS_ACCOUNTID}:role/Dynamo-${self:custom.appSync.serviceRole}"
resources:
  Resources:
    Vysae:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Vysae
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
              - AttributeName: PK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Dynamo-AppSyncServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "Dynamo-AppSyncServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:BatchGetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - "arn:aws:dynamodb:eu-west-1:*:table/Vysae"
                    - "arn:aws:dynamodb:eu-west-1:*:table/Vysae/*"

