// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e59133ae-fccc-422d-9ce4-e6368d7e3ad0",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_d9W2WnqzS",
    "aws_user_pools_web_client_id": "70ueie0aisuv3bmctj391me9jb",
    "aws_content_delivery_bucket": "vysae-hosting-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://vysae-hosting-dev.s3-website-eu-west-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://pg5uripmh5acbelm3g5yb2dyr4.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "linkShareholder",
            "endpoint": "https://5w3lx38chj.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
